### ISSUE TITLE
Update to 2.3.0

### ISSUE THREAD

**Issue by mrclary** [conda-forge/diskcache-feedstock#3]
diskcache is now at version 2.3.0. Can someone make the update on conda-forge?
I'm not sure how to modify the meta.yaml file, or I'd do it myself (I'm a newbie).

**Comment by pmlandwehr** [comment]
Thanks for the tip! Going to be a slow tick up, since I'll be handling the intermediate versions first.

**Comment by mrclary** [comment]
Let me know if there is anything I can do to help!

Thanks,
Ryan Clary
